repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
      - id: tflint
#  - repo: https://github.com/accurics/terrascan
#    rev: v1.12.0
#    hooks:
#      - id: terraform-pre-commit
#        args: ['-i terraform'] # Just scan for terraform code

# TODO: Uncomment the above lines after fix the vulnerabilities